In [1]:
import numpy as np

In [2]:
np.__version__


'2.3.1'

In [12]:
arr1 = np.array([1, 2, 3 ,4 ,5, 6])
arr1

array([1, 2, 3, 4, 5, 6])

In [5]:
type(arr1)


numpy.ndarray

In [6]:
arr1.shape

(5,)

In [7]:
arr1.dtype

dtype('int64')

In [9]:
arr1.ndim

1

In [13]:
arr1.size

6

In [15]:
arr2 = np.array([[1, 4, 5,], [6, 7, 4]])
arr2

array([[1, 4, 5],
       [6, 7, 4]])

In [16]:
arr2.ndim

2

In [17]:
arr2.shape

(2, 3)

In [23]:
arr3 = np.array([[[1, 4, 5,], [6, 7, 4]], [[3, 5, 4], [5, 8, 7]], [[1, 4, 5,], [6, 7, 4]]])

In [24]:
arr3

array([[[1, 4, 5],
        [6, 7, 4]],

       [[3, 5, 4],
        [5, 8, 7]],

       [[1, 4, 5],
        [6, 7, 4]]])

In [25]:
arr3.ndim

3

In [26]:
arr3.shape

(3, 2, 3)

In [27]:
arr3.size


18

In [28]:
randomArr = np.random.rand(3, 2, 3)

In [29]:
randomArr.shape

(3, 2, 3)

In [30]:
randomArr

array([[[0.81546473, 0.71611932, 0.79638838],
        [0.11231174, 0.6431421 , 0.46255842]],

       [[0.76086085, 0.94811931, 0.37677449],
        [0.46545727, 0.37123618, 0.49655916]],

       [[0.20858821, 0.53056378, 0.46600273],
        [0.90086314, 0.14886828, 0.42721739]]])

In [31]:
randomArr.dtype

dtype('float64')

In [32]:
zeroes = np.zeros((3,2, 3))
zeroes

array([[[0., 0., 0.],
        [0., 0., 0.]],

       [[0., 0., 0.],
        [0., 0., 0.]],

       [[0., 0., 0.],
        [0., 0., 0.]]])

In [33]:
zeroes.ndim

3

In [36]:
full = np.full((3, 2, 3), 8)
full

array([[[8, 8, 8],
        [8, 8, 8]],

       [[8, 8, 8],
        [8, 8, 8]],

       [[8, 8, 8],
        [8, 8, 8]]])

In [37]:
ones = np.ones((3, 2, 3))
ones

array([[[1., 1., 1.],
        [1., 1., 1.]],

       [[1., 1., 1.],
        [1., 1., 1.]],

       [[1., 1., 1.],
        [1., 1., 1.]]])

In [41]:
arr3[1:3]

array([[[3, 5, 4],
        [5, 8, 7]],

       [[1, 4, 5],
        [6, 7, 4]]])

In [43]:
a1 = np.random.rand(2, 3, 2)
a2 = np.random.rand(2, 3, 2)

In [44]:
a1

array([[[0.07828567, 0.01653853],
        [0.13903313, 0.34162304],
        [0.97413513, 0.61283297]],

       [[0.34951305, 0.29308838],
        [0.58032725, 0.58811318],
        [0.88099273, 0.40944733]]])

In [45]:
a2

array([[[0.66683719, 0.60465895],
        [0.96844934, 0.48312414],
        [0.68355738, 0.88231373]],

       [[0.80902578, 0.02015225],
        [0.90517587, 0.67041438],
        [0.33254016, 0.24406312]]])

In [46]:
np.add(a1, a2)

array([[[0.74512286, 0.62119748],
        [1.10748247, 0.82474718],
        [1.65769251, 1.4951467 ]],

       [[1.15853883, 0.31324062],
        [1.48550312, 1.25852757],
        [1.21353289, 0.65351045]]])

In [47]:
sqrt = np.sqrt(25)
abs = np.abs(-2)
power = np.power(2, 8)
log = np.log(25)
mins = np.min(a1)
maxs = np.max(a2)

In [48]:
sqrt


np.float64(5.0)

In [49]:
abs

np.int64(2)

In [50]:
power

np.int64(256)

In [51]:
log

np.float64(3.2188758248682006)

In [52]:
mins

np.float64(0.016538527774511813)

In [53]:
maxsa

NameError: name 'maxsa' is not defined

In [54]:
maxs

np.float64(0.9684493398907228)